apiVersion: v1
kind: Service
metadata:
  name: synapse
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: matrix
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: synapse
  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: 8008