apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: matrix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.synapse.storage.size | default "10Gi"}} # User defined, how much space of data, default 10Gi
{{- if .Values.synapse.storage.storageClassName }} # User defineed, namee of storage class, leeave empty to let k8s handle naming
  storageClassName: {{ .Values.synapse.storage.storageClassName }}
{{- end }}