apiVersion: v1
kind: Secret
metadata:
  name: synapse-recaptcha
type: Opaque
stringData:
  RECAPTCHA_SITE_KEY: "{{ .Values.synapse.recaptcha.siteKey }}"
  RECAPTCHA_SECRET_KEY: "{{ .Values.synapse.recaptcha.secretKey }}"
  REGISTRATION_SHARED_SECRET: "{{ .Values.synapse.registration_shared_secret}}"